config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users
resources :posts do
  resources :comments, :chars
end


get '/' => "posts#index"






end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/char.rb
class Char < ApplicationRecord

  belongs_to :post


  validates :user, presence: true
  validates :charname, presence: true
  validates  :power, presence: true
  validates  :dex, presence: true
  validates  :wiz, presence: true
  validates  :hp, presence: true

  validates  :uniname, presence: true
  validates   :charimg, presence: true
  validates_format_of :charimg,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"
  mount_uploader :charimg, CharimgUploader

end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :post


  validates :author, presence: true
  validates :text, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments
  has_many :chars

  
  validates :title, presence: true 
  validates :title, :length => {:minimum => 3, :maximum => 20} 
  validates :author, presence: true
  validates :content, presence: true
  validates :content, :length => {:minimum => 10, :maximum => 2000}
  validates :image, presence: true
  validates_format_of :image,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, :validatable


  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/chars_controller.rb
class CharsController < ApplicationController

  def new


  end

def create
 
    @post = Post.find(params[:post_id])
    @post.chars.create(char_params)
    @post.save

    redirect_to post_path(@post)
 
end

  def char_params
    params.require(:char).permit(:user, :charname, :power, :dex, :wiz, :hp, :uniname, :charimg)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new

end

def create
 
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)

    redirect_to post_path(@post)
 
end


   def comment_params
    params.require(:comment).permit(:author, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



def index
 @posts=Post.all


end


  def new
    
  end


  def create
    @post = Post.new(post_params)
      
      if  @post.save
        redirect_to @post
      else
        render action: 'new'
      end
  end


def show

  @post = Post.find(params[:id])
  @chars = @post.chars.where(user:[current_user.username])
  

  if @chars.count > 0
  @char = @chars.first
  @charc = @post.chars.all
 
end

end


def destroy
  @post = Post.find(params[:id])
  
  @post.comments.each do |comment|
    comment.destroy
  end

  @post.chars.each do |char|
    char.destroy
  end

  @post.destroy


  redirect_to posts_path

end


 private 

  def post_params
    params.require(:post).permit(:author, :content, :title, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def profile
  end


  def show
  end

  def del
  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chars_helper.rb
module CharsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DND</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

   

   

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


    <!--Bootstrap blog-->

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<!--fonts -->




   <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine">
     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ultra">
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ribeye">

       <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


        <link rel="stylesheet" href="http://bootstraptema.ru/plugins/2015/bootstrap3/bootstrap.min.css" />
        <link href="http://bootstraptema.ru/snippets/generator/2015/jquery-ui-git.css" rel="stylesheet" />
        <link href="http://bootstraptema.ru/snippets/generator/2015/jquery.colorpicker.css" rel="stylesheet" />
        <script type="text/javascript" src="http://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>

   

   <!--chat-->

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>

<!--charcreate-->

<script type="text/javascript" src ="/js/charstats.js"></script>



  </head>

  <body>
      <div class="background"></div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="mx-auto" style="width: 800px;">
<div id="welcome">
        <t2><%=current_user.username%></t2>
        
        <a href = <%=%>><t2>Мои игры</t2></a>
        <a href = <%=%>><t2>Профиль</t2></a>
        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></p2><hr/><br/>
</div>
</div>
<!--<p2> Привет, <%= current_user.username %>!<br/>
 <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></p2><br/><br/>-->


<games>    
<div class="container">
  
  <div class="row">
      <% @posts.reverse_each do |post| %>

                <div style="left: 100px" class="col-md-5 col-sm-7 col-xs-10">
                 
                  <imga class="img-responsive">
                     
                    
                        <h1 class="title">
                          <tw><%=post.title.capitalize%></tw>
                          
                        </h1>
                       
                          <a href=<%=post_url(post)%>><img class="img-responsive" src=<%=post.image%> >
                          </a>
                          <div  class="alert alert-secondary" role="alert">


                          <p2><%=post.content%></p2>
                       

                        <div class="info">
                        
                          
                          <a >Персонажей в игре: <%=post.chars.size-1%> </a><br/>
                          <a >ДМ: <%=post.author%> </a><br/>
                          <a ><%=post.created_at%> </a>
                          <div class="clearfix"></div>
                            <small> <span ></span> <%= link_to "В игру", post_url(post)%></small>
                            <%if current_user.username == post.author %>
                          <small><%= link_to "Удалить", post_path(post.id), method: :delete, data: {confirm: "Точно удалить?"} %>  <br/></small>
                          <%end%>
                        </div>
                        </div>
                          
                        
                  </imga>

              </div>
      <%end%>

  
  <div class="row">
     

                <div style="left: 120px"  class="col-md-5 col-sm-4 col-xs-10">
                 
                  <imga class="img-responsive">
                     
                    
                        <h1 class="title">
                          <a href=<%=new_post_url%>><tw> Новая игра</tw>
                          
                        </h1>
                       
                          <a href=<%=new_post_url%>><img class="img-responsive" src="/img/DND.jpg"  >
                          </a>
                          <div  class="alert alert-secondary" role="alert">


                          <p2>Создайте новый мир и пригласите в него игроков</p2>
                       

                          <div class="info">
                             
                        
                        
                            <div class="clearfix"></div>
                          </div>
                        
                          
                        
                  </imga>

              
      
        

 
</div>



</games>
             
                      


                    
           
       

app/views/posts/new.html.erb
<div id="post">
	<div class="mx-auto" style="width: 1000px;">
<t4> Создать новую игру: </t4>
<%= form_for :post, url: posts_path do |f| %> 

	
	<h1> <%= f.hidden_field  :author, value: current_user.username %> </h1>

	<t2> <%= f.label :Название_игры %> </t2>
	<p1> <%= f.text_area  :title, size: "50x1"  %> </p1><br/>

	<t2> <%= f.label :Описание_игры %> </t2>
	<p1> <%= f.text_area  :content, size: "80x10" %> </p1><br/>


	<t2><%= f.label :Выбрать_картинку %></t2>
    <p1><%= f.file_field :image %></p1>

	<p3> <%= f.submit 'Начать игру' %></p3>
 <%end%>
</div>
</div>

app/views/users/index.html.erb
<div class="mx-auto" style="width: 200px;">
 
<% if user_signed_in? %>
<div class="alert alert-secondary" role="alert">
     Привет, <%= current_user.username %>!
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %><br/><br/>
    <%= link_to 'Открыть', posts_path %>
</div>



<% else %>

<div class="alert alert-secondary" role="alert">
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
</div>    
<% end %>